name       : kontact
version    : 18.12.2
release    : 17
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.2/src/kontact-18.12.2.tar.xz : b512c1f5ae50dfa324c931853e1b5f1f64b5f3c873d3e5a93c917889d17c11be
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : office
summary    : Container application to unify several major PIM applications within one application
description: |
    Kontact is the integrated solution to your personal information management (PIM) needs. It combines well-known KDE applications like KMail, KOrganizer and KAddressBook into a single interface to provide easy access to mail, scheduling, address book and other PIM functionality.
builddeps  :
    - pkgconfig(Qt5WebEngine)
    - akonadi-devel
    - extra-cmake-modules
    - grantleetheme-devel
    - kcmutils-devel
    - kcompletion-devel
    - kconfigwidgets-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdepim-apps-libs-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kitemmodels-devel
    - kontactinterface-devel
    - kparts-devel
    - kpimtextedit-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - libboost-devel
    - libkdepim-devel
rundeps    :
    - akregator
    - kaddressbook
    - kmail
    - knotes
    - korganizer
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
