name       : kontact
version    : 19.08.3
release    : 28
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.3/src/kontact-19.08.3.tar.xz : 2bc81b4c051856894d5405532e9663a59abf25bfed1cf0394ee24e219b4752d5
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : office
summary    : Container application to unify several major PIM applications within
    one application
description: |
    Kontact is the integrated solution to your personal information management (PIM) needs. It combines well-known KDE applications like KMail, KOrganizer and KAddressBook into a single interface to provide easy access to mail, scheduling, address book and other PIM functionality.
builddeps  :
    - pkgconfig(Qt5WebEngine)
    - akonadi-devel
    - extra-cmake-modules
    - grantleetheme-devel
    - kcmutils-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdepim-apps-libs-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kitemmodels-devel
    - kontactinterface-devel
    - kparts-devel
    - kpimtextedit-devel
    - kwindowsystem-devel
    - libboost-devel
    - libkdepim-devel
rundeps    :
    - akregator
    - kaddressbook
    - kmail
    - knotes
    - korganizer
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
