name       : kontact
version    : 22.04.3
release    : 62
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.3/src/kontact-22.04.3.tar.xz : 78eee72e657c1e71593fd3122a5573ba503c4bee1391e4f462d608ba2127fbc7
homepage   : https://kde.org/applications/office/org.kde.kontact
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : office
summary    : Container application to unify several major PIM applications within one application
description: |
    Kontact is the integrated solution to your personal information management (PIM) needs. It combines well-known KDE applications like KMail, KOrganizer and KAddressBook into a single interface to provide easy access to mail, scheduling, address book and other PIM functionality.
builddeps  :
    - pkgconfig(Qt5WebEngine)
    - kcmutils-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kcontacts-devel
    - kdoctools-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kmime-devel
    - kontactinterface-devel
    - kparts-devel
    - kpimtextedit-devel
    - libkdepim-devel
    - pimcommon-devel
rundeps    :
    - akregator
    - kaddressbook
    - kmail
    - knotes
    - korganizer
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
