name       : kontact
version    : 20.04.0
release    : 33
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.0/src/kontact-20.04.0.tar.xz : bb09ace130e98ad718b06d20e63fcd91bd60ee1ca52cb123c657325a83ed63f0
homepage   : https://kde.org/applications/office/org.kde.kontact
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : office
summary    : Container application to unify several major PIM applications within one application
description: |
    Kontact is the integrated solution to your personal information management (PIM) needs. It combines well-known KDE applications like KMail, KOrganizer and KAddressBook into a single interface to provide easy access to mail, scheduling, address book and other PIM functionality.
builddeps  :
    - pkgconfig(Qt5WebEngine)
    - akonadi-devel
    - extra-cmake-modules
    - grantleetheme-devel
    - kcmutils-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdepim-apps-libs-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kitemmodels-devel
    - kontactinterface-devel
    - kparts-devel
    - kpimtextedit-devel
    - kwindowsystem-devel
    - libboost-devel
    - libkdepim-devel
rundeps    :
    - akregator
    - kaddressbook
    - kmail
    - knotes
    - korganizer
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
