name       : kontact
version    : 17.12.3
release    : 6
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.3/src/kontact-17.12.3.tar.xz : 5af9a17cad2038db690254409302e2091e8b8c0f54035a69fb71f44a102c333e
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.1
component  : office
summary    : Container application to unify several major PIM applications within one application
description: |
    Kontact is the integrated solution to your personal information management (PIM) needs. It combines well-known KDE applications like KMail, KOrganizer and KAddressBook into a single interface to provide easy access to mail, scheduling, address book and other PIM functionality.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5WebEngine)
    - akonadi-devel
    - extra-cmake-modules
    - grantleetheme-devel
    - kcmutils-devel
    - kcompletion-devel
    - kconfigwidgets-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdepim-apps-libs-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kitemmodels-devel
    - kontactinterface-devel
    - kparts-devel
    - kpimtextedit-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - libboost-devel
    - libkdepim-devel
rundeps    :
    - akregator
    - kaddressbook
    - kmail
    - knotes
    - korganizer
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
