name       : kontact
version    : 18.08.1
release    : 12
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.1/src/kontact-18.08.1.tar.xz : 784b5db77ee95ece82d0bffe0cacb25766f679b8854152186d4c38fe4c76da8c
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.1
component  : office
summary    : Container application to unify several major PIM applications within one application
description: |
    Kontact is the integrated solution to your personal information management (PIM) needs. It combines well-known KDE applications like KMail, KOrganizer and KAddressBook into a single interface to provide easy access to mail, scheduling, address book and other PIM functionality.
builddeps  :
    - pkgconfig(Qt5WebEngine)
    - akonadi-devel
    - extra-cmake-modules
    - grantleetheme-devel
    - kcmutils-devel
    - kcompletion-devel
    - kconfigwidgets-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdepim-apps-libs-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kitemmodels-devel
    - kontactinterface-devel
    - kparts-devel
    - kpimtextedit-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - libboost-devel
    - libkdepim-devel
rundeps    :
    - akregator
    - kaddressbook
    - kmail
    - knotes
    - korganizer
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
